[[redirects]]
  from = "/api/*"
  to = "https://api.football-data.org/v2/:splat"
  status = 200
  headers = {X-Auth-Token = "API_TOKEN"}

[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200